spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-person
          uri: lb://ms-person
          predicates:
            - Path=/person/**

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/

server:
  port: 8080
