spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  config:
    enabled: true
    uri: http://api-gateway:8080
  gateway:
    discovery:
      locator:
        enabled: true
    routes:
      - id: ms-person
        uri: lb://ms-person
        predicates:
          - Path=/api/person/**

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/

server:
  port: 8080
