spring:
  data:
    mongodb:
      #authentication-database: admin
      database: admin
      port: 27017
      host: mongo-database
      #username: root
      #password: 1234

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8090
