spring:
  data:
    mongodb:
      #authentication-database: admin
      database: admin
      port: 27017
      host: mongo-database
      #username: root
      #password: 1234

server:
  port: 8080
