spring:
  data:
    mongodb:
      database: Project1DB
      port: 27017

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

my:
  property:
    URL_GATEWAY: "http://localhost:8080"

server:
  port: 8114
